"""Vendor-neutral Intermediate Representation (IR)."""

from .capabilities import Capability, IRCapability
from .confidence import Confidence, ConfidenceLevel, min_confidence
from .diff import EntityRef, IRDiff, Modified, diff_ir
from .entities import (
    AttachKind,
    Client,
    ClientKind,
    Device,
    DeviceRole,
    DhcpScope,
    L3Intf,
    L3Role,
    Link,
    LinkKind,
    Port,
    PortMode,
    StpMode,
    Vlan,
    client_id,
    device_id,
    link_id,
    port_id,
)
from .indexes import (
    access_ports_by_vlan,
    clients_by_ap,
    clients_by_port,
    clients_by_vlan,
    exits_by_vlan,
    node_for,
    ports_by_device,
    vc_root_map,
)
from .model import IR, IR_VERSION, IRBuilder, IRValidationError
from .provenance import CONFIG_META, OBSERVED_META, FactMeta, Provenance, fact_meta

__all__ = [
    "IR",
    "IR_VERSION",
    "IRBuilder",
    "IRValidationError",
    "IRCapability",
    "Capability",
    "Confidence",
    "ConfidenceLevel",
    "min_confidence",
    "Provenance",
    "FactMeta",
    "fact_meta",
    "CONFIG_META",
    "OBSERVED_META",
    "Device",
    "DeviceRole",
    "Port",
    "PortMode",
    "Link",
    "LinkKind",
    "Vlan",
    "DhcpScope",
    "L3Intf",
    "L3Role",
    "Client",
    "ClientKind",
    "AttachKind",
    "StpMode",
    "device_id",
    "port_id",
    "link_id",
    "client_id",
    "EntityRef",
    "Modified",
    "IRDiff",
    "diff_ir",
    "vc_root_map",
    "node_for",
    "ports_by_device",
    "access_ports_by_vlan",
    "exits_by_vlan",
    "clients_by_port",
    "clients_by_ap",
    "clients_by_vlan",
]
